# Gráficos complejos

En esta clase vamos a aprender a hacer gráficos complejos con Altair. Gráficos compuestos por más de una capa, visualizaciones compuestas por más de un gráfico y exploraremos como crear gráficos interactivos.

**Información importante**

* Documentación oficial de Altair: https://altair-viz.github.io/index.html

* Espacio de trabajo de Notion de la clase: https://bit.ly/tacosdedatos-notion

* Donde encontrar este _binder_: https://bit.ly.com/dataviz-demo

## Por explorar hoy
* Gráficos compuestos (capas y concatenaciones)
* Facetas
* Tooltips
* Interactividad

* ejemplo 1: https://altair-viz.github.io/gallery/airports_count.html 
* ejemplo 2: https://altair-viz.github.io/gallery/selection_histogram.html

In [ ]:
import altair as alt
import pandas as pd 
from vega_datasets import data as vega_data
data = vega_data.gapminder()

In [ ]:
mi_pais = 'India'

In [ ]:
datos_de_mi_pais = data[data['country'] == mi_pais]
datos_de_mi_pais

     year country  cluster         pop  life_expect  fertility
341  1955   India        0   393000000       40.249     5.8961
342  1960   India        0   434000000       43.605     5.8216
343  1965   India        0   485000000       47.193     5.6058
344  1970   India        0   541000000       50.651     5.2640
345  1975   India        0   607000000       54.208     4.8888
346  1980   India        0   679000000       56.596     4.4975
347  1985   India        0   755000000       58.553     4.1500
348  1990   India        0   839000000       60.223     3.8648
349  1995   India        0   927000000       61.765     3.4551
350  2000   India        0  1007702000       62.879     3.1132
351  2005   India        0  1080264388       64.698     2.8073

In [ ]:
alt.Chart(datos_de_mi_pais).mark_bar(fill = '#D47AE8').encode(
    x = alt.X('year:O', title = '', axis = alt.Axis(labelAngle=0, labelFontSize=12)),
    y = alt.Y('pop:Q', title = 'Población', axis = alt.Axis(format = ".2s", grid=False, titleAnchor='end', titleAngle = 0)),
).properties(
    title = f"Población de {mi_pais} de 1955 a 2005",
    width = 600,
).configure_title(
    fontSize = 18,
    anchor = 'start',
).configure_view(
    strokeWidth=0
)

alt.Chart(...)